services:
  - type: web
    name: esc-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn escsite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: escsite.settings
